# Generated by Django 3.0.3 on 2023-02-10 10:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200221_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='check_out',
            field=models.DateField(default=datetime.datetime(2023, 2, 12, 10, 31, 35, 569806, tzinfo=utc)),
        ),
    ]
